package org.isa.nuh;

public interface SPController {

    String URL = "http://192.168.1.13:8000";

    String LOGIN = "LOGIN";
    String IS_LOGGED_IN = "IS_LOGGED_IN";

    String USERNAME = "USERNAME";
    String PASSWORD = "PASSWORD";

    String LATITUDE = "LATITUDE";
    String LONGITUDE = "LONGITUDE";

    String HELP_CATEGORIES = "HELP_CATEGORIES";

    String ACCOMODATION_NEED = "ACCOMODATION_NEED";
    String FOOD_NEED = "FOOD_NEED";
    String CLOTHES_NEED = "CLOTHES_NEED";
    String MEDICINE_NEED = "MEDICINE_NEED";
    String OTHER_NEED = "OTHER_NEED";

    String ACCOMODATION_NEED_TEXT = "ACCOMODATION_NEED_TEXT";
    String FOOD_NEED_TEXT = "FOOD_NEED_TEXT";
    String CLOTHES_NEED_TEXT = "CLOTHES_NEED_TEXT";
    String MEDICINE_NEED_TEXT = "MEDICINE_NEED_TEXT";
    String OTHER_NEED_TEXT = "OTHER_NEED_TEXT";
}
