package org.isa.nuh;

public interface SPController {

    String LOGIN = "LOGIN";
    String IS_LOGGED_IN = "IS_LOGGED_IN";

    String HELP_CATEGORIES = "HELP_CATEGORIES";

    String ACCOMODATION_NEED = "ACCOMODATION_NEED";
    String FOOD_NEED = "FOOD_NEED";
    String CLOTHES_NEED = "CLOTHES_NEED";
    String MEDICINE_NEED = "MEDICINE_NEED";
    String VOLUNTEER_NEED = "VOLUNTEER_NEED";
    String OTHER_NEED = "OTHER_NEED";

    String ACCOMODATION_NEED_TEXT = "ACCOMODATION_NEED_TEXT";
    String FOOD_NEED_TEXT = "FOOD_NEED_TEXT";
    String CLOTHES_NEED_TEXT = "CLOTHES_NEED_TEXT";
    String MEDICINE_NEED_TEXT = "MEDICINE_NEED_TEXT";
    String VOLUNTEER_NEED_TEXT = "VOLUNTEER_NEED_TEXT";
    String OTHER_NEED_TEXT = "OTHER_NEED_TEXT";

}
